export default [
  "    XXX              X   X    ",
  "   X   X             X   X    ",
  "   X   X             X   X    ",
  "       X             X   X    ",
  "       X             X   X    ",
  "       X   XXX    XXXX   X    ",
  "     XX   X   X  X   X   X    ",
  "       X  X   X  X   X   X    ",
  "       X  X      X   X   X    ",
  "       X   XXX   X   X   X    ",
  "       X      X  X   X   X    ",
  "   X   X  X   X  X   X   X    ",
  "   X   X  X   X  X   X   X    ",
  "    XXX    XXX    XXX X   X   ",
];
